# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
