# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160324_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.TextField(default=datetime.datetime(2016, 3, 24, 8, 53, 46, 144000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
